os: linux
dist: bionic

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - main
    - dev

cache:
  directories:
    - $HOME/.composer/cache

########################
# Default dist builds. #
########################
php:
  - 7.3
  - 7.2
  - 7.1

#######################
# Custom dist builds. #
#######################
jobs:
  include:

    # PHP versions 7.4 and 8.0 already supported by the Focal dist.
    # https://docs.travis-ci.com/user/reference/focal/#php-support
  - name: "PHP: 8.0" # Nightly is PHP 8.0 since Feb 2019.
    php: nightly
    dist: focal
    # install:
    # - composer update --ignore-platform-reqs
  - php: 7.4
    dist: focal

    # PHP versions 7.0 and 5.6 last supported by the Xenial dist.
    # https://docs.travis-ci.com/user/reference/bionic/#php-support
    # https://docs.travis-ci.com/user/reference/xenial/#php-support
  - php: 7.0
    dist: xenial
  - php: 5.6
    dist: xenial
  - php: 5.6
    dist: xenial

  allow_failures:
  - php: nightly

before_install:
  # Speed up build time by disabling Xdebug.
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  - phpenv config-rm xdebug.ini || echo "xdebug not available for PHP $TRAVIS_PHP_VERSION"

install:
  # Remove PHPStan WordPress for PHP less than 7.1.
  - if [[ $TRAVIS_PHP_VERSION = "5.6" || $TRAVIS_PHP_VERSION = "7.0" ]]; then composer remove --dev szepeviktor/phpstan-wordpress; fi
  # Composer install.
  - composer install

script:
  # Search for PHP syntax errors.
  - find -L . -path ./vendor -prune -o -name \*.php -print0 | xargs -0 -n 1 -P 4 php -l
  # Show a list of installed coding standards.
  - composer lint-i
  # Run against installed coding standards.
  - composer lint
  # Run PHPStan only for PHP greater or equal to 7.1.
  # Suppress temporarily from travis.
  - if [[ $TRAVIS_PHP_VERSION != "5.6" && $TRAVIS_PHP_VERSION != "7.0" ]]; then composer stan; fi
