name: Test Convert PT AO90

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    paths:
      # Any change to a PHP file should run checks.
      - '**.php'
      # These files configure Composer. Changes could affect the outcome.
      - 'composer.*'
      # This file configures PHPStan. Changes could affect the outcome.
      - 'phpstan.neon'
      # Changes to workflow files should always verify all workflows are successful.
      - '.github/workflows/*.yml'
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  # Runs the Conversion Tests.
  #
  # Outputs Build and Conversion errors.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up PHP.
  # - Logs debug information.
  # - Installs Composer dependencies (use cache if possible).
  # - Make Composer packages available globally.
  # - Builds the Replace Pairs set of rules.
  # - Test the Convert PT AO90 on a set of text strings agains expected results.
  test:
    name: Convert to PT AO90 (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1'] # 7.4 is the minimum supported version.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@2.25.2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
        env:
          fail-fast: false

      - name: Log debug information
        run: |
          php --version
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Make Composer packages available globally
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Build Replace Pairs JSON file (PHP ${{ matrix.php-versions }})
        run: composer build-replace-pairs

      - name: Run Convert PT AO90 test (PHP ${{ matrix.php-versions }})
        run: composer test
